sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
services:
  - mongodb
jdk:
  - oraclejdk7
  - openjdk7

script:
  - export TRAVIS_PULL_REQUEST="false"
  - ./travis.sh

branches:
  only:
    - master
