sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/node_modules'
services:
  - mongodb
jdk:
  - oraclejdk7

script: ./travis.sh

branches:
  only:
    - master

before_script:
  - "npm install"
